#!/bin/bash
#
# Copyright 2012 Eugene Wissner <belka.ew@gmail.com>
# Available under the terms of the GNU GPL.
#

NAME="libsecret"
VERSION="0.16"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/${NAME}/${VER_MAJ}.${VER_MIN}/${NAME}-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource

if [ "$DLG_ARCH" == "x86-64" ]; then
	host="x86_64-slackware-linux"
else
	host="i486-slackware-linux"
fi
configure --disable-debug \
	--build=$host
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
