wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-multilib.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-serverbin-compat.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-no-export-ssllibs.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-lpr-help.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-peercred.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-pid.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-strict-ppd-line-length.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-logrotate.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-usb-paperout.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-res_init.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-filter-debug.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-uri-compat.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-str3382.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-hp-deviceid-oid.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-ricoh-deviceid-oid.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-systemd-socket.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-lpd-manpage.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-usblp-quirks.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-enum-all.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-use-ipp1.1.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-no-gcry.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-ipp-multifile.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-web-devices-timeout.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-final-content-type.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-journal.patch
wget https://raw.githubusercontent.com/PhantomX/slackbuilds/master/cups/patches/cups-synconclose.patch
