#!/bin/bash
#
# Copyright 2004-2007 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="libsoup"
VERSION="2.44.2"
REVISION="1"

PKG_SOURCEURL='$DLG_GNOMEMIRROR/$NAME/$VER_MAJ.$VER_MIN/$NAME-$VERSION.tar.xz'
PKG_SANIFYNOTOUCH="bla"

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure
make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
