#!/bin/bash
#
# Copyright 2004, 2007-2012 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="gst-plugins-base1"
VERSION="1.2.3"
REVISION="1"

PKG_SOURCEURL='http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='yes'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
cxxflags
prepare
analyzesource
configure --enable-introspection=yes \
	--enable-profiling \
	--enable-iso-codes \
	--with-package-name="\"Dropline Gnome GStreamer Base Plugins ${VERSION}"\" \
	--with-package-origin="\"http://www.droplinegnome.org"\"

make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
