#!/bin/bash
#
# Copyright 2004 Dagmar d'Surreal <rivyqntzne@tznvy.pbz>
# Available under the terms of the GNU GPL.
#

NAME="gst-plugins-good1"
VERSION="1.2.3"
REVISION="1"

PKG_SOURCEURL='http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-${VERSION}.tar.xz'
PKG_SANIFYNOTOUCH='ohyeah'

. $DLG_ROOT/etc/config
. $DLG_ROOT/lib/dl-base

cflags
prepare
analyzesource
configure --enable-introspection \
	--enable-profiling \
	--with-package-name="\"Dropline Gnome GStreamer Base Plugins ${VERSION}"\" \
	--with-package-origin="\"http://www.droplinegnome.org"\"

make
makeinstall install-strip
tidydocumentation
analyzebinaries
finalizepackage
packagize
cleanup
